apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-name
  labels:
    replica-set-key: replica-set-value
spec:
  replicas: 2
  selector:
    matchLabels:
      pod-key: pod-value
  template:
    metadata: 
      # POD details
      name: pod-name
      labels:
        pod-key: pod-value
    spec:
      containers:
        - name: container-name
          image: coolgourav147/nginx-custom
          resources:
            limits:
              memory: 60Mi
              cpu: "1"
            requests:
              memory: 56Mi
              cpu: "0.2"
          env:
            - name: env-variable-name
              value: env-variable-value
            - name: country
              value: usa

