apiVersion: v1
kind: Service
metadata:
  name: service-name
  labels:
    # Key: Value
    servicelabel: label-value
spec:
  type: NodePort
  ports:
  - nodePort: 32000
    port: 8000
    targetPort: 80
  selector:
    # Label as in the POD
    type: my-first-pod