apiVersion: v1
kind: Pod
metadata: 
  name: pod-name
  namespace: namespace-name
  labels:
    # Key:
    pod-key: pod-value
    pod-key2: pod-value2
spec:
  containers:
    - name: container-name
      image: coolgourav147/nginx-custom
      resources:
        limits: # Maximum resources
          memory: 512Mi
          cpu: "1"
        requests: # Minimum resources
          memory: 256Mi # G, M, Mi, Gi etc
          cpu: "0.2" # Gi,Mi etc
      env:
        - name: env-variable-name
          value: env-variable-value
        - name: country
          value: usa